### ISSUE TITLE
Guidelines 

### ISSUE THREAD

**Issue by jiin-kim109** [sfuSwSo/swe-resume-evaluator#12]
**Description:**
The Guidelines component is a static component that has no props or actions. It will be used solely for visual purposes.

In our wireframe, the Guidelines component will be placed below the dropzone component. It provides guidance to users before they upload their resumes.

![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/57239105/5277f026-5210-4171-85a3-78b33922ac94)

Refer the following as an example,
![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/57239105/9db46680-1ddd-4314-a71d-e1fce2518167)

The component consists of
- **Title**
e.g. "Guidelines for uploading your resume"
- **Header text**
e.g. "To make sure we analyze your resume correctly and generate the right recommendations, please ensure that the resume you upload meets the following guidelines"
- **Wrapper box**
- **Guidelines**

Unfortunately, we don't have a high-level prototype on Figma, so it is hard to define the detailed styling at this moment. Therefore, this ticket only expects the existence of the above four components, and the rest of the styling will be up to the assignee.

**Acceptance Critiera:**

- Add the Guidelines component to `src/components/`.
- Write a JSDoc comment on the component illustrating what this component is about.
- Write a test with Jest and RTL to verify its rendering.

**Comment by GripenANM** [comment]
the layout is so triggering , like why centre the text?

**Comment by jiin-kim109** [comment]
@GripenANM Yeah that's true, but we don't have our sample either. For now, we'll use that image as a reference to reduce confusion and fix the details later.

**Comment by GripenANM** [comment]
@heyj0jo 

![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/65241893/4a7aa8b3-e61e-4be6-a12a-ac8463ceead7)

Interactions/behaviour follow this https://mantine.dev/others/dropzone/

details and hex code + fonts + icons here:

https://www.figma.com/file/ZNq9QCo0FYrodu7HO1zolv/ResumeEvaluator-UI---Mantine-UI-Design-System---v5.10?type=design&node-id=207%3A11826&mode=design&t=U8CXZUv6fh6Dv3k1-1

**Comment by heyj0jo** [comment]
@GripenANM wait your design doesn't have Guidelines component. Which design should I refer to?

Never mind

**Comment by GripenANM** [comment]
![Uploading Screenshot_20231008_231211_Edge.jpg…]()

I mean it really just a title plus the text in side the display for the stepper body. Should be relatively simple. Check the mantine UI guidelines for the typography and icons
