### ISSUE TITLE
Dropzone

### ISSUE THREAD

**Issue by jiin-kim109** [sfuSwSo/swe-resume-evaluator#13]
**Description:**

The Dropzone component supports users to upload their file with a simple drag and drop method. 

Check it out in our wireframe:
![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/57239105/9371d108-b9dd-4c75-8567-7c4db953e3c1)

The Dropzone consists of the three components
- Dropzone box with dotted border
- Manual upload button
- "Drag file to window" text

You may use an external library to implement the Dropzone component. Please ensure that your chosen library is well-maintained and has a sufficient number of community supporters.

An example Dropzone can be found at:
https://yuvaleros.github.io/material-ui-dropzone/

![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/57239105/46b334c8-764b-44d3-8c80-1db4665aa55e)

The Dropzone component should support the following props:
**onSubmit(filepath: string)** Default: (fp) => null
_Type: function_
Invoked when a file is uploaded to the dropzone ~~via drag and drop or~~  via the upload button. It calls the provided function with an argument of the local file path to the uploaded file.

**Acceptance Critiera:**

- Add a Dropzone component to `src/components/`.
- Define prop types using the PropTypes package.
- Write a JSDoc comment on the component, illustrating what the component is about and the props it supports.
- Write a test with Jest and RTL to verify its rendering. **You must use Jest Mocking in order to test OnSubmit props.**

**Comment by jiin-kim109** [comment]
@dp357 sorry for any inconvenience. This component doesn't actually support drag and drop. The drag and drop feature will be supported by the Drag and Drop Indicator component. This component only indicates that drag and drop is possible. You are only required to implement the upload button, which opens the file explorer to select a file and returns a file path (this is a browser feature), and invokes the onSubmit prop.

**Comment by dp357** [comment]
@jiin-kim109 Ok. I will only implement an upload button in the Dropzone component then.

**Comment by jiin-kim109** [comment]
@dp357 yes thanks, drag & drop is unnecessary, but you still need to implement the file selection feature using <input type="file" .. /> tag. For example,
https://medium.com/web-dev-survey-from-kyoto/how-to-customize-the-file-upload-button-in-react-b3866a5973d8

Also, I might be wrong in the prop definition because there's a built-in "File" object type in browser Javascript. so you may implement the prop as,
onSubmit(~~filepath: string~~) 
to
onSubmit(file: File)

**Comment by dp357** [comment]
Thanks for clarification. I was confused in the onSubmit prop part. Now I can store uploaded file state as a File object instead of filepath string?

**Comment by jiin-kim109** [comment]
@dp357 Yup exactly. I wrote the prop definitions because we are in the first iteration and it might be difficult to some members to write a component from scratch, but they seem to be somehow opinionated. The more legit requirement was supposed to be: **"Allow other components to pass a callback that is invoked with a file data that user has selected by the upload button."**. You can implement it in anyway you want as long as it comes with a clear documentation.

**Comment by dp357** [comment]
@jiin-kim109 I almost finished the implementation of the upload button on my branch (will do jsdoc and jest later).

1. The uploaded file by a user is stored as a File object instead of a file path 
2. When a file is uploaded, its details will be displayed below (only file name for now) so the user can confirm before continuing
3. When the user clicks on the Evaluate button (below the file details), pass the File object to handleFile function (passed to Dropzone by other components) -> let other components handle the API stuff

![Screenshot 2023-10-06 184616](https://github.com/sfuSwSo/swe-resume-evaluator/assets/122840079/a578bc89-0ba5-4526-b3c5-594ef0f14acd)

Let me know if you need any changes.

**Comment by jiin-kim109** [comment]
@dp357 yes but the third one shouldn’t be needed. The callback that is passed by other components should be invoked immediately after uploading the file, and you have to write a Jest test for this using Jest Mocking (jest.fn)
https://jestjs.io/docs/mock-functions

https://stackoverflow.com/questions/45867095/test-react-component-method-is-calling-function-pass-as-a-prop

**Comment by dp357** [comment]
@jiin-kim109 Okay. I got it. I thought users have to click on a button to redirect them to the Reporting page. So when user upload a file, just display the file details,  invoke callback, then they have to manually click on the Reporting page to  see the results?

**Comment by jiin-kim109** [comment]
@dp357 exactly.

**Comment by jiin-kim109** [comment]
@dp357 the user workflow hasn’t been decided in detailed yet but yeah when a user uploads a file, the callback is immediately invoked with the File object and the file detail shows up. The transition to the reporting page afterward is not a concern of the Dropzone component.

**Comment by dp357** [comment]
@jiin-kim109 thanks for the clarification. I was confused about that part.

**Comment by jiin-kim109** [comment]
@dp357 

The following tutorials will help. Please read them in order.
**What is Jest and RTL?**
https://blog.logrocket.com/testing-react-apps-jest-react-testing-library/

**Mocking callback prop**
https://arthurpedroti.com.br/mocking-and-testing-libraries-functions-with-react-testing-library-and-jest/

These are further references:
**Jest Mocking**
https://jestjs.io/docs/mock-functions

**RTL Cheatsheet**
https://testing-library.com/docs/react-testing-library/cheatsheet

**RTL and Jest for React Hooks**
https://chanonroy.medium.com/mocking-hooks-for-testing-with-jest-and-react-testing-library-d34505616d12

**Comment by dp357** [comment]
@jiin-kim109 Thanks Jin! I'll look into them.
