### ISSUE TITLE
PDF to tokens

### ISSUE THREAD

**Issue by Pentaminum** [sfuSwSo/swe-resume-evaluator#5]
Description: 

Create a py file under `python/` that takes a user input for a file path to local pdf and outputs a list of tokens.

The .py script should perform the following procedures:

1. Take a user input indicating a file path to a local pdf file. Using a Python IO, load a pdf file to memory. 
- If a file is not a pdf file, raise an exception.
- User input should be given as an argument to a function. This means you must write and export a function that takes a user input as its argument.
- A sample resume pdf file is given under `python/resources/sample_resume.pdf`

2. Read all the lines from the pdf file and convert them into a raw string.

3. Tokenize the raw string and export (return).

How to tokenize:
reference: https://spacy.io/api/token

example:
![Image](https://github.com/sfuSwSo/swe-resume-evaluator/assets/32114064/07890514-add4-4587-9dda-5df91dd249c4)

ex)  The PDF file contains a sentence "I'm a man."
-> [ "I", "'m", "a", "man", "." ] 

Acceptance Criteria: 
- the function returns a list of tokens(string)
- the token contains all strings in the pdf dile

**Comment by GripenANM** [comment]
I can do it
