### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by jiin-kim109** [sfuSwSo/swe-resume-evaluator#9]
**If you'd like to assign this ticket to yourself, please inform @jiin-kim109 to obtain the Firebase credentials and admin permission on the Firebase dashboard.**

## Description

For fast-paced development, we will be using Firebase as our authentication service provider. With the Firebase-provided SDK, your task is to implement an authentication API endpoint in Express.js.

**Firebase Config**
```
import { initializeApp } from "firebase/app";
const firebaseConfig = {
  apiKey: "SEALED",
  authDomain: "SEALED",
  projectId: "SEALED",
  storageBucket: "SEALED",
  messagingSenderId: "SEALED",
  appId: "SEALED"
};
const app = initializeApp(firebaseConfig);
```

</details>

**Do not directly embed the Firebase credentials in your code.** Rename .env.example file to .env and fill the credentials in there. Use `dotenv` library to retrieve credential data from .env file locally.
https://www.npmjs.com/package/dotenv

This API should expose the following endpoints to users:

**_POST /auth/signup_**
<details>
  <summary>API Details</summary>

_Request Header_
```
{}
```
_Request Body_
 
```
{
    username: string
    email: string
    password: string
}
```
_Response Header_
```
{}
```
_Response Body_
**success - status 200**
```
json
{
    message: "ok",
    status: 200,
    user_token: string
}
```
**failed - status 400**
```
json
{
    message: [Error_message],
    status: 400
}
```

</details>

<br />

**_POST /auth/login_**
<details>
  <summary>API Details</summary>

_Request Header_
```
Authentication: Bearer [user_token]
```

_Request Body_
```
{}
```

_Response Header_
```
{}
```

_Response Body_
**success - status 200**
```
{
    message: "ok",
    status: 200
}
```
**failed - status 400**
```
{
    message: [Error_message],
    status: 400
}
```
</details>

Create a `server/auth/` directory and a file `auth.js` in it. Implement the authentication APIs above and router in `app.js`. Each API should follow the data type schema above. For example, if user gives a number to the username or email field, the response should be a failed response with status code 400, and a message indicates that the values to the fields have failed on validation.

Response should always come with message (string) and status (number). Additional fields can be added as /auth/signup response if needed.

You can refer to the following articles for the signup feature:
https://dev.to/deepakshisood/authentication-using-firebase-for-expressjs-2l48

For the login feature using an Authentication Bearer header, you can check out:
https://medium.com/@harunrst11/id-token-authentication-with-firebase-node-js-explained-github-9ff86578ed89

## Acceptance Criteria

- Implement the /auth route and /auth/signup and /auth/login APIs. Implement an ExpressJS router in app.js. Use Postman for local testing.
- Ensure that the APIs support and provide responses as illustrated above. Test the features with Firebase dashboard to ensure the creation of a new user and authentication via JWT token work.
- Each data field for the POST requests should undergo validation before processing. This means that if a user enters a number in the username field, the client should receive a response with a status code of 400 and a message indicating which field failed validation.

- The email field should be validated to ensure the string value follows an email format (e.g., name@domain).
- If an email is already signed up, and a user already exists in Firebase, the API should respond with a 400 status code and a message indicating that a user has already signed up.

- The password should be at least 8 characters long.

- The username should be equal to or more than 4 characters long and must contain at least one alphabet character.
- Usernames cannot be duplicated.

- **Write a Jest Unit Test for each of the endpoint. Check this article for Jest tests with Express JS.**
https://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest/

- **Do not directly embed the Firebase credentials in your code.** Rename .env.example file to .env and fill the credentials in there. Use `dotenv` library to retrieve credential data from .env file locally.

**Comment by GripenANM** [comment]
Just use your own tokens and make sure not to commit it to the repo. Use Env values

**Comment by jiin-kim109** [comment]
@GripenANM Tokens are made on server when a new user is created, and it'll be stored in users' local browser.

**Comment by GripenANM** [comment]
@jiin-kim109 i mean the api key and private key for firebase

**Comment by jiin-kim109** [comment]
@GripenANM Yes there'll be a ticket coming up in later iteration regarding writing a script that generates env file from Github environment variables in Github workflow and publish to GIthub Release. It's too big for the first iteration if both of these combine.

**Comment by GripenANM** [comment]
just use env.local for dev :)
